window.noname_update={
	version:'1.9.120.22',
	update:'1.9.120',
	changeLog:[
		'新增程咬金',
	],
	files:[
		'image/character/chengyaojin.jpg',
		'image/character/wuzhaoxiang.jpg',
		'image/character/fengdi.jpg',
		'image/character/weizhaoxiang.jpg',
		'character/sb.js',
		'character/daba.js',
		'character/liaoyuan.js',
		'game/config.js',
		'game/package.js',
		'game/source.js',
		'game/game.js',
		'character/shenhua.js',
		'image/character/dachu.jpg',
		'image/character/mushuihan.jpg',
		'image/character/gaohuan.jpg',
		'image/character/huanshi.jpg',
		'image/character/yuwentai.jpg'
	]
};
